version: "3.7"
services:
  #############################################################################################
  ###                                         API                                           ###
  #############################################################################################
  dpia-api:
    container_name: dpia-api
    build:
      context: .
      dockerfile: ./src/backend/.docker/Dockerfile.dev
    volumes:
      # Binds the application folder from the host inside the container enabling hot reloading
      - ./src/backend:/usr/src/app
      # Ignores the node_modules of the host and uses it's own instead
      - /usr/src/app/node_modules
    networks:
      - dpia-network
    ports:
      - "3000:3000"
  
  #############################################################################################
  ###                                       Frontend                                        ###
  #############################################################################################
  dpia-frontend:
    container_name: dpia-frontend
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
    networks:
      - dpia-network
    ports:
      - "8080:8080"
    tty: true
  
networks:
  dpia-network: 
    driver: "bridge"
