apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPLICATION_NAME}-template
labels:
  template: ${APPLICATION_NAME}-template
objects:
- kind: Task
  apiVersion: tekton.dev/v1beta1
  metadata:
    annotations:
      tekton.dev/displayName: openshift client
      tekton.dev/pipelines.minVersion: 0.12.1
      tekton.dev/tags: cli
    name: process-${APPLICATION_NAME}-template-${ENVIRONMENT}
    namespace: ${LICENSE_PLATE}-tools
    labels:
      app.kubernetes.io/version: '0.1'
      operator.tekton.dev/provider-type: redhat
      DataClass: Low
      name: dpia-deploy
  spec:
    description: >-
      This task uses the openshift cli to process and apply the raw template for
      the DPIA API to the aa77ab DEV namespace
    steps:
      - image: 'image-registry.openshift-image-registry.svc:5000/openshift/cli:latest'
        name: ${APPLICATION_NAME}
        resources: {}
        script: >
          oc process -f https://raw.githubusercontent.com/bcgov/cirmo-dpia/main/openshift/templates/api/emerald/api-dc-template-v3.yaml 
          -p APPLICATION_NAME=${APPLICATION_NAME}
          -p ENVIRONMENT=${ENVIRONMENT}
          -p LICENSE_PLATE=${LICENSE_PLATE} 
          -p IMAGESTREAM='dpia-dev' 
          -p DATACLASS='Medium'
          | oc apply -f -

parameters:
  - description: Application Name
    displayName: AppName
    name: APPLICATION_NAME
    required: true
    value: dpia-api
  - description: Environment
    displayName: Environment
    name: ENVIRONMENT
    required: true
    value: dev
  - description: License Plate
    displayName: License Plate
    name: LICENSE_PLATE
    required: true
    value: aa77ab