apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"tekton.dev/v1beta1","kind":"Pipeline","metadata":{"annotations":{},"labels":{"DataClass":"low","name":"dpia-deploy","template":"dpia-api-template"},"name":"dpia-api-deploy-dev","namespace":"aa77ab-tools"},"spec":{"tasks":[{"name":"process-dpia-api-template-dev","taskRef":{"kind":"Task","name":"process-dpia-api-template-dev"}}]}}
  resourceVersion: '330408667'
  name: process-apply-dpia-service
  generation: 1
  namespace: aa77ab-tools
  labels:
    DataClass: Low
    name: process-apply-dpia-service
spec:
  params:
    - name: environment
      type: string
      default: ""
    - name: application
      type: string
      default: ""
    - name: image
      type: string
      default: ""
  tasks:
    - name: process-apply-dpia-service
      taskRef:
        kind: Task
        name: process-apply-dpia-service
      params:
        - name: environment
          value: $(params.environment)
        - name: application
          value: $(params.application)
        - name: image
          value: $(params.image)