apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${APPLICATION_NAME}-github-actions-rolebinding-template
labels:
  template: ${APPLICATION_NAME}-github-actions-rolebinding-template
objects:
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: Github-Actions-Admin
    namespace: ${NAMESPACE}-${ENVIRONMENT}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - kind: ServiceAccount
    name: github-actions
    namespace: ${NAMESPACE}-${ENVIRONMENT}

parameters:
  - description: Application Name
    displayName: AppName
    name: APPLICATION_NAME
    required: true
    value: dpia
  - description: Environment
    displayName: Environment
    name: ENVIRONMENT
    required: true
    value: tools
  - description: Namespace 
    displayName: Namespace
    name: NAMESPACE 
    required: true
    value: b996e6
