name: "Frontend e2e Test Suite"

on:
  workflow_dispatch:

jobs:
  frontend-e2e:
    environment: APP-Test
    runs-on: ubuntu-latest
    steps:
      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Navigate to frontend dir, install dependencies, execute cypress command
      - name: Setup and Execute WebDriverIO e2e test suite
        shell: bash
        env:
          mpoPass : ${{ secrets.MPO_IDIR_PASSWORD }}
          cpoPass : ${{ secrets.CPO_IDIR_PASSWORD }}
          drafterPass : ${{ secrets.DRAFT_IDIR_PASSWORD }}
        run: |
           cd ./src/frontend
           npm install
           mpoPass=$mpoPass cpoPass=$cpoPass drafterPass=$drafterPass npm run wdio-test
        
      #Generate Cucumber report and upload artifact  
      - name: Generate Cucumber report and upload artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-artifact
          path: ./src/frontend/test/reporter/htmlreport/
