name: API - Docker Image Build
on:
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - "src/backend/**"
  # push:
  #   branches: [ main ]
  #   paths:
  #     - "src/backend/**"
  workflow_dispatch:

jobs:
  api-image-build:
    name: api-image-build
    runs-on: ubuntu-latest
    steps:
    
      - name: Pull Git repo.
        uses: actions/checkout@v2
        
      - name: Build the Docker image
        run: |
          docker-compose build dpia-webapp
