name: 'Frontend Pull Request Lint'
on:
  pull_request:
    branches: [ 'main' ]
    paths:
      - "src/frontend/**"
  workflow_dispatch:

jobs: 
  APP-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Project Dependencies
        run: |
          cd src/frontend
          npm ci

      - name: Run lint
        run: | 
          npm run lint
