name: DEV Build and Deploy DPIA WebApp

on:
  push:
    branches: [main]
    paths:
      - "src/frontend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Hello, world!
        run: |
          echo "Hello, world!"

