name: Github Environment - DPIA API 

on:
  push:
    branches: [main]
    paths:
      - "src/backend/**"
  workflow_dispatch:
  
jobs:
  DPIA-API-Build-Tag-Push:
    environment: API-Dev
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Cluster Login -> TOOLS Namespace
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_TOOLS_SA_PASSWORD }}"}'
          cmd: |
            'version'
            
      - name: Login to Openshift Docker
        run : |
          docker login ${{ secrets.OPENSHIFT4_PUBLIC_IMAGE_REPOSITORY_BASE_URL }} -u ${{ secrets.OPENSHIFT4_TOOLS_SA_USERNAME }} -p ${{ secrets.OPENSHIFT4_TOOLS_SA_PASSWORD }}
          
      - name: Build the Docker image
        run: |
          docker-compose build dpia-api
      
      - name: Docker List Images
        run: |
          docker image ls 
          
      - name: Set Commit Hash for Image Tag
        run: |
          commit_hash=$(echo $(git rev-parse --short HEAD))
          echo "pull_request_hash=$commit_hash" >> $GITHUB_ENV
          
      - name: Create JSON file for Image Tag State
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: 'pull-request.json'
          json: '{ "hash":"${{ env.pull_request_hash }}" }'
          
      - name: Upload JSON file
        uses: actions/upload-artifact@v3
        with: 
          name: pull-request.json
          path: pull-request.json
      
      - name: Docker Tag Version
        run: |
          docker tag cirmo-dpia_dpia-api ${{ secrets.OPENSHIFT4_API_PUBLIC_IMAGE_REPOSITORY }}:${{ env.pull_request_hash }}
      
      - name: Docker List Images
        run: |
          docker image ls 
          
      - name: Docker Push Version
        run: |
          docker push ${{ secrets.OPENSHIFT4_API_PUBLIC_IMAGE_REPOSITORY }}:${{ env.pull_request_hash }}
          
  DEV-deploy:
    runs-on: ubuntu-latest
    environment: API-Dev
    needs: [DPIA-API-Build-Tag-Push]
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Cluster Login -> DEV Namespace
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_SA_PASSWORD }}"}'
          cmd: |
            'version'
            
      - name: Download JSON artifact
        uses: actions/download-artifact@v3
        with:
          name: pull-request.json
          
      - name: Read JSON File
        id: json-file
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'pull-request.json'
          prop_path: 'hash'
          
      - name: Set Commit Hash Value to Environment
        run: |
          commit_hash=$(echo ${{ steps.json-file.outputs.prop }})
          echo "pull_request_hash=$commit_hash" >> $GITHUB_ENV
 
      - name: Get Previous Deployment Hash Value
        run: |
          dc_name=$(echo $(oc get dc --namespace=${{ secrets.OPENSHIFT_DEV_NAMESPACE }} -l app=dpia-api | awk 'FNR == 2 {print $1}'))
          echo "previous_dc_name=$dc_name" >> $GITHUB_ENVf
    
      - name: Create new JSON file for current and Previous Deployment Hash
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: 'dev-deploy.json'
          json: '{ "hash":"${{ env.pull_request_hash }}", "dc_name":"${{ env.previous_dc_name}}"}'

      - name: Upload JSON file
        uses: actions/upload-artifact@v3
        with: 
          name: dev-deploy.json
          path: dev-deploy.json
            
      - name: Process and Apply API DeploymentConfig, Service, Route templates
        env:
          NAMESPACE: "${{ secrets.OPENSHIFT_DEV_NAMESPACE }}"
          APPLICATION_NAME: "${{ secrets.APPLICATION_NAME }}"
          LICENSE_PLATE: "${{ secrets.LICENSE_PLATE }}"
          ENVIRONMENT: "${{ secrets.ENVIRONMENT }}"
          DC_TEMPLATE: "api-dc-template.yaml"
          SERVICE_TEMPLATE: "api-service-template.yaml"
          ROUTE_TEMPLATE: "api-route-template.yaml"
          DIR: "api"
          IMAGE_TAG: ${{ env.pull_request_hash }}
        run: |
          ./.github/helpers/deploy.sh 
    
  DEV-health-check:
    runs-on: ubuntu-latest
    environment: API-Dev
    needs: [DEV-deploy]
    steps:
    
      - uses: actions/checkout@v2
    
      - name: Cluster Login -> DEV Namespace
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_SA_PASSWORD }}"}'
          cmd: |
            'version'

      - name: Download JSON artifact
        uses: actions/download-artifact@v3
        with:
          name: dev-deploy.json
          
      - name: Read JSON File
        id: json-file-hash
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'dev-deploy.json'
          prop_path: 'hash'
          
      - name: Set Commit Hash Value to Environment
        run: |
          commit_hash=$(echo ${{ steps.json-file-hash.outputs.prop }})
          echo "pull_request_hash=$commit_hash" >> $GITHUB_ENV
            
      - name: Health Check DEV deployment
        env:
          NAMESPACE: "${{ secrets.OPENSHIFT_DEV_NAMESPACE }}"
          APPLICATION_NAME: "${{ secrets.APPLICATION_NAME }}"
          LICENSE_PLATE: "${{ secrets.LICENSE_PLATE }}"
          ENVIRONMENT: "${{ secrets.ENVIRONMENT }}"
          IMAGE_TAG: "${{ env.pull_request_hash }}"
        run: |
          ./.github/helpers/application-health.sh

  DEV-cleanup:
    runs-on: ubuntu-latest
    environment: API-Dev
    needs: [DEV-health-check]
    steps:

      - uses: actions/checkout@v2

      - name: Cluster Login
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_SA_PASSWORD }}"}'
          cmd: |
            'version'

      - name: Download JSON artifact
        uses: actions/download-artifact@v3
        with:
          name: dev-deploy.json

      - name: Read JSON File - hash value
        id: json-file-hash
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'dev-deploy.json'
          prop_path: 'hash'
          
      - name: Read JSON File - previous deployment hash
        id: json-file-previous-deploy
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'dev-deploy.json'
          prop_path: 'dc_name'

      - name: Set Commit Hash Value and Previous Deploy Name to Environment
        run: |
          commit_hash=$(echo ${{ steps.json-file-hash.outputs.prop }})
          echo "pull_request_hash=$commit_hash" >> $GITHUB_ENV
          dc_name=$(echo ${{ steps.json-file-previous-deploy.outputs.prop }})
          echo "previous_deploy_name=$dc_name" >> $GITHUB_ENV

      - name: Cleanup Previous Deployment Config
        env:
          NAMESPACE: "${{ secrets.OPENSHIFT_DEV_NAMESPACE }}"
          OBJECT_NAME: "${{ env.previous_deploy_name }}"
        run: |
          ./.github/helpers/cleanup.sh

  TEST-tag-dpia-api-image:
    environment: API-Test
    runs-on: ubuntu-latest
    needs: [DEV-cleanup]
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Cluster Login -> TOOLS Namespace
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_TOOLS_SA_PASSWORD }}"}'
          cmd: |
            'version'
            
      - name: Login to Openshift Docker
        run : |
          docker login ${{ secrets.OPENSHIFT4_PUBLIC_IMAGE_REPOSITORY_BASE_URL }} -u ${{ secrets.OPENSHIFT4_TOOLS_SA_USERNAME }} -p ${{ secrets.OPENSHIFT4_TOOLS_SA_PASSWORD }}
        
      - name: Download JSON artifact
        uses: actions/download-artifact@v3
        with:
          name: dev-deploy.json
          
      - name: Read JSON File
        id: json-file
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'dev-deploy.json'
          prop_path: 'hash'
          
      - name: Set Commit Hash Value and Previous Deploy Name to Environment
        run: |
          commit_hash=$(echo ${{ steps.json-file.outputs.prop }})
          echo "pull_request_hash=$commit_hash" >> $GITHUB_ENV
          dc_name=$(echo ${{ steps.json-file-previous-deploy.outputs.prop }})
          echo "previous_deploy_name=$dc_name" >> $GITHUB_ENV
        
      - name: Update tag for Imagestream
        env:
          TOOLS_NAMESPACE: "${{ secrets.TOOLS_NAMESPACE }}"
          DPIA_COMPONENT: "dpia-api"
          HASH_IMAGE: "${{ env.pull_request_hash }}"
          ENVIRONMENT: "test"
        run: |
          ./.github/helpers/tag-imagestream.sh
          
  TEST-deploy:
    environment: API-Test
    runs-on: ubuntu-latest
    needs: [TEST-tag-dpia-api-image]
    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v2 
        
      - name: Cluster Login -> TEST Namespace
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_SA_PASSWORD }}"}'
          cmd: |
            'version'
        
      - name: Download JSON artifact
        uses: actions/download-artifact@v3
        with:
          name: dev-deploy.json
          
      - name: Read JSON File
        id: json-file
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'dev-deploy.json'
          prop_path: 'hash'
          
      - name: Set Commit Hash Value to Environment
        run: |
          commit_hash=$(echo ${{ steps.json-file.outputs.prop }})
          echo "pull_request_hash=$commit_hash" >> $GITHUB_ENV
      
      - name: Process and Apply API DeploymentConfig, Service, Route templates
        env:
          NAMESPACE: "${{ secrets.OPENSHIFT_DEV_NAMESPACE }}"
          APPLICATION_NAME: "${{ secrets.APPLICATION_NAME }}"
          LICENSE_PLATE: "${{ secrets.LICENSE_PLATE }}"
          ENVIRONMENT: "${{ secrets.ENVIRONMENT }}"
          DC_TEMPLATE: "api-dc-template.yaml"
          SERVICE_TEMPLATE: "api-service-template.yaml"
          ROUTE_TEMPLATE: "api-route-template.yaml"
          DIR: "api"
          IMAGE_TAG: ${{ env.pull_request_hash }}
        run: |
          ./.github/helpers/deploy.sh 
          
  TEST-health-check:
    runs-on: ubuntu-latest
    environment: API-Test
    needs: [TEST-deploy]
    steps:
    
      - uses: actions/checkout@v2
    
      - name: Cluster Login
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_SA_PASSWORD }}"}'
          cmd: |
            'version'

      - name: Download JSON artifact
        uses: actions/download-artifact@v3
        with:
          name: dev-deploy.json
          
      - name: Read JSON File
        id: json-file-hash
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'dev-deploy.json'
          prop_path: 'hash'
          
      - name: Set Commit Hash Value to Environment
        run: |
          commit_hash=$(echo ${{ steps.json-file-hash.outputs.prop }})
          echo "pull_request_hash=$commit_hash" >> $GITHUB_ENV
            
      - name: Health Check TEST deployment
        env:
          NAMESPACE: "${{ secrets.OPENSHIFT_TEST_NAMESPACE }}"
          APPLICATION_NAME: "${{ secrets.APPLICATION_NAME }}"
          LICENSE_PLATE: "${{ secrets.LICENSE_PLATE }}"
          ENVIRONMENT: "${{ secrets.ENVIRONMENT }}"
          IMAGE_TAG: "${{ env.pull_request_hash }}"
        run: |
          ./.github/helpers/application-health.sh

  TEST-cleanup:
    runs-on: ubuntu-latest
    environment: API-Test
    needs: [TEST-health-check]
    steps:

      - uses: actions/checkout@v2

      - name: Cluster Login
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_SA_PASSWORD }}"}'
          cmd: |
            'version'

      - name: Download JSON artifact
        uses: actions/download-artifact@v3
        with:
          name: dev-deploy.json

      - name: Read JSON File - hash value
        id: json-file-hash
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'dev-deploy.json'
          prop_path: 'hash'
          
      - name: Read JSON File - previous deployment hash
        id: json-file-previous-deploy
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'dev-deploy.json'
          prop_path: 'dc_name'

      - name: Set Commit Hash Value and Previous Deploy Name to Environment
        run: |
          commit_hash=$(echo ${{ steps.json-file-hash.outputs.prop }})
          echo "pull_request_hash=$commit_hash" >> $GITHUB_ENV
          dc_name=$(echo ${{ steps.json-file-previous-deploy.outputs.prop }})
          echo "previous_deploy_name=$dc_name" >> $GITHUB_ENV

      - name: Cleanup Previous Deployment Config
        env:
          NAMESPACE: "${{ secrets.OPENSHIFT_TEST_NAMESPACE }}"
          OBJECT_NAME: "${{ env.previous_deploy_name }}"
        run: |
          ./.github/helpers/cleanup.sh
    
  PROD-tag-dpia-api-image:
    environment: API-Prod
    runs-on: ubuntu-latest
    needs: [TEST-cleanup]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0

      - name: Find Tag
        id: tagger
        run: |
          git config --global user.email ${{ secrets.GLOBAL_USER_EMAIL }}
          git config --global user.name ${{ secrets.GLOBAL_USER_NAME }}
          git describe --tags --abbrev=0
          tag=$(git describe --tags --abbrev=0)
          echo "latest_tag=$tag" >> $GITHUB_ENV

      - name: Cluster Login -> TOOLS Namespace
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_TOOLS_SA_PASSWORD }}"}'
          cmd: |
            'version'

      - name: Login to Openshift Docker
        run : |
          docker login ${{ secrets.OPENSHIFT4_PUBLIC_IMAGE_REPOSITORY_BASE_URL }} -u ${{ secrets.OPENSHIFT4_TOOLS_SA_USERNAME }} -p ${{ secrets.OPENSHIFT4_TOOLS_SA_PASSWORD }}

      - name: Download JSON artifact
        uses: actions/download-artifact@v3
        with:
          name: dev-deploy.json

      - name: Read JSON File
        id: json-file
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'dev-deploy.json'
          prop_path: 'hash'

      - name: Set Commit Hash Value to Environment
        run: |
          commit_hash=$(echo ${{ steps.json-file.outputs.prop }})
          echo "pull_request_hash=$commit_hash" >> $GITHUB_ENV

      - name: Promote Test tag to Prod
        env:
          TOOLS_NAMESPACE: "${{ secrets.TOOLS_NAMESPACE }}"
          DPIA_COMPONENT: "dpia-api"
          HASH_IMAGE: "${{ env.pull_request_hash }}"
          ENVIRONMENT: "prod"
        run: |
          ./.github/helpers/tag-imagestream.sh

      - name: Increment Git Repo Tag Patch +1
        env:
          TAG: ${{ env.latest_tag }}
          EMAIL: ${{ secrets.GLOBAL_USER_EMAIL }}
          NAME: ${{ secrets.GLOBAL_USER_NAME }}
        run: |
          ./.github/helpers/increment-tag.sh -p

      - name: Find New Tag
        run: |
          git config --global user.email ${{ secrets.GLOBAL_USER_EMAIL }}
          git config --global user.name ${{ secrets.GLOBAL_USER_NAME }}
          tag_two=$(git describe --tags --abbrev=0)
          echo "new_tag=$tag_two" >> $GITHUB_ENV

      - name: Promote Prod tag to version 
        env:
          TOOLS_NAMESPACE: "${{ secrets.TOOLS_NAMESPACE }}"
          DPIA_COMPONENT: "dpia-api"
          HASH_IMAGE: "${{ env.pull_request_hash }}"
          VERSION: "${{ env.new_tag }}"
        run: |
          ./.github/helpers/tag-imagestream-release.sh

      - name: Create new JSON file Prod Deploy Version
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: 'prod-version.json'
          json: '{ "version-tag":"${{ env.new_tag }}"}'

      - name: Upload JSON file
        uses: actions/upload-artifact@v3
        with: 
          name: prod-version.json
          path: prod-version.json
          
  PROD-deploy:
    environment: API-Prod
    runs-on: ubuntu-latest
    needs: [PROD-tag-dpia-api-image]
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2 

      - name: Cluster Login -> PROD Namespace
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_SA_PASSWORD }}"}'
          cmd: |
            'version'

      - name: Download JSON artifact
        uses: actions/download-artifact@v3
        with:
          name: prod-version.json

      - name: Read JSON File
        id: json-file
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'prod-version.json'
          prop_path: 'version-tag'

      - name: Set Commit Hash Value to Environment
        run: |
          version_tag=$(echo ${{ steps.json-file.outputs.prop }})
          echo "image_tag=$version_tag" >> $GITHUB_ENV

      - name: Deploy to PROD
        env:
          NAMESPACE: "${{ secrets.OPENSHIFT_PROD_NAMESPACE }}"
          APPLICATION_NAME: "${{ secrets.APPLICATION_NAME }}"
          LICENSE_PLATE: "${{ secrets.LICENSE_PLATE }}"
          ENVIRONMENT: "${{ secrets.ENVIRONMENT }}"
          DC_TEMPLATE: api-dc-template-prod.yaml
          IMAGE_TAG: ${{ env.image_tag }}
          DIR: "api"
        run: |
          ./.github/helpers/deploy-prod.sh 
  
  PROD-health-check:
    runs-on: ubuntu-latest
    environment:
      name: API-Prod
      url: https://dpia-api-prod.apps.silver.devops.gov.bc.ca/api/v1/api-docs
    needs: [PROD-deploy]
    steps:
    
      - uses: actions/checkout@v2
    
      - name: Cluster Login
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT4_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT4_SA_PASSWORD }}"}'
          cmd: |
            'version'
            
      - name: Health Check PROD deployment
        env:
          NAMESPACE: "${{ secrets.OPENSHIFT_PROD_NAMESPACE }}"
          APPLICATION_NAME: "${{ secrets.APPLICATION_NAME }}"
          LICENSE_PLATE: "${{ secrets.LICENSE_PLATE }}"
          ENVIRONMENT: "${{ secrets.ENVIRONMENT }}"
        run: |
          ./.github/helpers/application-health.sh
